name: pug_vpn
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cryptography: ^2.7.0
  http: ^1.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/pug_vpn.png
    - assets/images/pug_icon.png
    - assets/images/world_map.png
    - assets/images/connection_board.png
    - assets/images/onboarding_pug.png

    - assets/pug_countries/pug_auto.png
    - assets/pug_countries/pug_finland.png
    - assets/pug_countries/pug_germany.png
    - assets/pug_countries/pug_usa.png

    - assets/flags/usa_flag.png
    - assets/flags/finland_flag.png
    - assets/flags/germany_flag.png

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  image_path: "assets/app_icon.png"
