name: pug_vpn_backend
description: Backend API for the PugVPN Flutter client.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  dart_frog: ^1.1.0
  crypto: ^3.0.6
  postgres: ^3.5.9

dev_dependencies:
  lints: ^5.0.0
